# Generated by Django 6.0.1 on 2026-01-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('width', models.PositiveIntegerField()),
                ('profile', models.PositiveIntegerField()),
                ('diameter', models.PositiveIntegerField()),
                ('load_index', models.PositiveIntegerField()),
                ('speed_index', models.CharField(max_length=2)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('allseason', 'All Season')], default='summer', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tires', to='catalog.brand')),
            ],
            options={
                'verbose_name': 'Tire',
                'verbose_name_plural': 'Tires',
                'ordering': ['brand__name', 'model_name'],
            },
        ),
    ]
