# Generated by Django 6.0.1 on 2026-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
