# Generated by Django 6.0.1 on 2026-01-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_disk_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(db_index=True, max_length=100)),
                ('car', models.CharField(db_index=True, max_length=100)),
                ('year', models.CharField(db_index=True, max_length=50)),
                ('modification', models.CharField(max_length=200)),
                ('pcd', models.CharField(blank=True, max_length=50)),
                ('center_bore', models.CharField(blank=True, max_length=50)),
                ('bolt_type', models.CharField(blank=True, max_length=100)),
                ('oem_tires', models.TextField(blank=True)),
                ('replacement_tires', models.TextField(blank=True)),
                ('tuning_tires', models.TextField(blank=True)),
                ('oem_wheels', models.TextField(blank=True)),
                ('replacement_wheels', models.TextField(blank=True)),
                ('tuning_wheels', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Car Fitment',
                'verbose_name_plural': 'Car Fitments',
                'ordering': ['vendor', 'car', 'year'],
                'indexes': [models.Index(fields=['vendor', 'car'], name='catalog_car_vendor_c087d3_idx'), models.Index(fields=['vendor', 'car', 'year'], name='catalog_car_vendor_e3b00e_idx')],
            },
        ),
    ]
