# Generated by Django 6.0.1 on 2026-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_carfitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='studded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tire',
            name='vehicle_type',
            field=models.CharField(choices=[('passenger', 'Легковий'), ('suv', 'Позашляховик'), ('truck', 'Вантажний'), ('van', 'Мікроавтобус')], default='passenger', max_length=20),
        ),
    ]
