# Generated by Django 6.0.1 on 2026-02-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_tire_studded_tire_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('code', models.CharField(help_text='Наприклад: kiev_Склад Колёс, kh_DTW Харьков (21 день)', max_length=200, unique=True, verbose_name='Код з прайсу')),
                ('is_preorder', models.BooleanField(default=False, help_text="Якщо True - товар показується як 'Під замовлення'", verbose_name='Під замовлення')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, help_text='Націнка на ціну постачальника', max_digits=5, verbose_name='Націнка %')),
                ('delivery_days', models.CharField(default='1-3 дні', help_text='Відображається на сайті', max_length=50, verbose_name='Термін доставки')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивні постачальники не імпортуються', verbose_name='Активний')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Вищий пріоритет = перевага при однаковій ціні', verbose_name='Пріоритет')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='disk',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disks', to='catalog.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='tire',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tires', to='catalog.supplier', verbose_name='Постачальник'),
        ),
    ]
