# Generated by Django 6.0.1 on 2026-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_supplier_disk_supplier_tire_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Постачальник', 'verbose_name_plural': 'Постачальники'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='priority',
        ),
    ]
