# Generated by Django 6.0.1 on 2026-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_supplier_options_remove_supplier_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупівельна ціна'),
        ),
        migrations.AddField(
            model_name='tire',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупівельна ціна'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Продажна ціна'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Продажна ціна'),
        ),
    ]
