# Generated by Django 5.1.15 on 2026-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_disk_purchase_price_tire_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показувати на головній сторінці', verbose_name='Рекомендований'),
        ),
        migrations.AddField(
            model_name='tire',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показувати на головній сторінці', verbose_name='Рекомендований'),
        ),
    ]
