# Generated by Django 5.1.15 on 2026-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='disk_type',
            field=models.CharField(choices=[('alloy', 'Литі'), ('steel', 'Штамповані'), ('forged', 'Ковані')], default='alloy', max_length=20),
        ),
        migrations.AlterField(
            model_name='tire',
            name='season',
            field=models.CharField(choices=[('summer', 'Літні'), ('winter', 'Зимові'), ('allseason', 'Всесезонні')], default='summer', max_length=20),
        ),
        migrations.AlterField(
            model_name='tire',
            name='studded',
            field=models.CharField(choices=[('none', 'Не шип'), ('studdable', 'Під шип'), ('studded', 'Шип')], default='none', max_length=20, verbose_name='Шипування'),
        ),
    ]
